# Generated by Django 4.2.7 on 2023-11-28 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_d_assurance_sociale', models.CharField(max_length=50)),
                ('date_de_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('adresse', models.TextField()),
                ('numero_de_telephone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacieProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('numero_de_telephone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrestataireSoinsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('numero_de_telephone', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_reclame', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_reclamation', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patientprofile')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prestatairesoinsprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_reclame', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_reclamation', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medicament')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patientprofile')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pharmacieprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_debut', models.DateField()),
                ('date_de_fin', models.DateField()),
                ('type_de_couverture', models.CharField(max_length=100)),
                ('prime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patientprofile')),
            ],
        ),
    ]
